[package]
name = "diem-stdlib"
dialect = "diem"
account_address = "0x2f66c09143acc52a85fec529a4e20c85"
dependencies = [
    { git = "https://github.com/taoheorg/move-stdlib", tag="diem-framework-v1.2.0" }
]
