[package]
name = "DiemCoreFramework"
version = "1.5.0"
dialect = "diem"

[addresses]
Std = "0x1"
DiemFramework = "0x1"
DiemRoot = "0xA550C18"
TreasuryCompliance = "0xB1E55ED"
CurrencyInfo = "0xB1E55ED"
VMReserved = "0x0"

[dependencies]
MoveStdlib = { git = "https://github.com/taoheorg/move-stdlib", rev="2f2639bbecb5c7fdaa66a5deaed5b8015ec858cd"}
